apiVersion: v1
kind: Service
metadata:
  name: posts-srv
  labels:
    app: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # match devbelopment pods with this label
  ports: # you can copy paste the same thing here to other services
    - port: 4000 # do not have to be identical, this is the NodePort port
      targetPort: 4000 # actual port for our application
      protocol: TCP
      name: posts # name is used to identify the port in the pod spec (no big difference)