apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: blog_services:latest
      imagePullPolicy: Never
      command: ["yarn", "posts"]
      # ports:
      #   - containerPort: 4000
      #     protocol: TCP