apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
build:
  local:
    push: false # disable pushing to docker registry
  artifacts: # images automatically built from source
    - image: blog_client
      context: blog
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js' # sync all js files in src folder
            dest: .
    - image: blog_services
      context: services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .